// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // FIX: web apiKey was incorrectly set to an OAuth client ID.
  // Correct apiKey is the Browser key from Firebase Console.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAPdveiSboNzDa3UEHRjvVFT-6USDes9o',
    appId: '1:16913759444:web:083fe11341f416eeffcf41',
    messagingSenderId: '16913759444',
    projectId: 'cyborgai-d7a18',
    authDomain: 'cyborgai-d7a18.firebaseapp.com',
    storageBucket: 'cyborgai-d7a18.firebasestorage.app',
    measurementId: 'G-W4615VT3MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHk930-B7gMUABsdctbVcuDnASdSZ4JjA',
    appId: '1:16913759444:android:b5436cbccd77fdd6ffcf41',
    messagingSenderId: '16913759444',
    projectId: 'cyborgai-d7a18',
    storageBucket: 'cyborgai-d7a18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNoRZWQb2n9BeTium0NM2mFVpBt6BlLB0',
    appId: '1:16913759444:ios:7cba5fa2e21245e1ffcf41',
    messagingSenderId: '16913759444',
    projectId: 'cyborgai-d7a18',
    storageBucket: 'cyborgai-d7a18.firebasestorage.app',
    androidClientId: '16913759444-alq5dkh3lfk99ip32s850uqfkiaqubtd.apps.googleusercontent.com',
    iosClientId: '16913759444-afu5636l7l3hv4vns3cqk3b2kerukh5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.cyborg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNoRZWQb2n9BeTium0NM2mFVpBt6BlLB0',
    appId: '1:16913759444:ios:7cba5fa2e21245e1ffcf41',
    messagingSenderId: '16913759444',
    projectId: 'cyborgai-d7a18',
    storageBucket: 'cyborgai-d7a18.firebasestorage.app',
    androidClientId: '16913759444-alq5dkh3lfk99ip32s850uqfkiaqubtd.apps.googleusercontent.com',
    iosClientId: '16913759444-afu5636l7l3hv4vns3cqk3b2kerukh5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.cyborg',
  );

  // FIX: updated appId to the new Windows app registered by flutterfire CLI
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAPdveiSboNzDa3UEHRjvVFT-6USDes9o',
    appId: '1:16913759444:web:17b998c99e91eb9cffcf41',
    messagingSenderId: '16913759444',
    projectId: 'cyborgai-d7a18',
    authDomain: 'cyborgai-d7a18.firebaseapp.com',
    storageBucket: 'cyborgai-d7a18.firebasestorage.app',
    measurementId: 'G-KJMT7TK0JV',
  );
}